# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9cb57f8b4d389682a5bae75351b718ad43045481a8d63ff9a9b874359c1de642cb6eade7c1da612a5f9a4dc869e5eb5d6d9ab4d0f29f105b1537bf312ce841b

test:
  secret_key_base: 837ae5288e2fcd1dbf7abed8a3973f8feecec47576cd3c4fbc41ba231aab3d2f7c8b7f8be683cfec6a85a18534c08a134c4a94ff43fd7afc4159092d32a98483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
